### ISSUE TITLE
creating tags and groups

### ISSUE THREAD

**Issue by michael-mueller** [die-wegmeister/Wegmeister.TagManager#1]
I try to get your package working in neos 3.x.. after changing the namespaces the tag-selector shows up in the neos backend... how can i create new tags and groups? is there a backend for that?

i can not type something in the corresponding field and directly add a new tag

**Comment by michael-mueller** [comment]
i just found out that the "TagManager" Role needs to be assigned to the user.. but still the backend module is not loaded... any advice?

**Comment by michael-mueller** [comment]
fixed.. my settings.yaml was not propperly formated

**Comment by Benjamin-K** [comment]
Dear Michael,

i will update the package soon to be working with neos 3.0. If you only need tags, this package will be fine. But if you need additional information (links for each tag for example) you should consider using nodes for this. Maybe i will get the time to write a node based package that can be used for that.

Best Regards
